# Generated by Django 5.2.5 on 2026-02-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=20, unique=True)),
                ('client', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('CRITIQUE', 'Critique (2h)'), ('HAUTE', 'Haute (4h)'), ('MOYENNE', 'Moyenne (24h)'), ('FAIBLE', 'Faible (48h)')], default='MOYENNE', max_length=10)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('ESCALADE', 'Escaladé'), ('RESOLU', 'Résolu')], default='OUVERT', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('resolu_par_n1', models.BooleanField(default=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
