# Generated by Django 5.2.5 on 2026-02-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('TECHNIQUE', 'Guide Technique'), ('UTILISATEUR', 'Guide Utilisateur'), ('PROCEDURE', 'Procédure Interne')], default='TECHNIQUE', max_length=20)),
                ('contenu', models.TextField(help_text='Décrivez ici la solution pas à pas')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('auteur', models.CharField(default='Aboubacar Sidick', max_length=100)),
            ],
            options={
                'verbose_name': 'Fiche Technique',
                'verbose_name_plural': 'Base de Connaissances',
            },
        ),
    ]
