# Generated by Django 5.2.5 on 2026-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='produit',
            field=models.CharField(choices=[('moya_collecte', 'MKS banking'), ('ivoire_pass', 'MKS pay')], default='moya_collecte', max_length=20),
        ),
    ]
