# Generated by Django 5.2.5 on 2026-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='suggestions_autre',
            field=models.TextField(blank=True, help_text="Si 'Autre', décrivez ici.", null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type_probleme',
            field=models.CharField(choices=[('PANNE_GENERALE', "Le site/application ne s'ouvre plus"), ('PAIEMENT_ECHOUE', 'Problème de paiement FinTech'), ('CONNEXION', 'Impossible de se connecter (Login)'), ('LENTEUR', "L'application est lente"), ('MIS_A_JOUR', 'Bug après une mise à jour'), ('AUTRE', 'Autre (Précisez ci-dessous)')], default='AUTRE', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='produit',
            field=models.CharField(choices=[('moya_collecte', 'moya collecte'), ('ivoire_pass', 'ivoire pass')], default='moya_collecte', max_length=20),
        ),
    ]
