# Generated by Django 5.2.5 on 2026-03-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_suggestions_autre_ticket_type_probleme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
    ]
